sudo: true

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

cache:
    directories:
    - $HOME/.composer/cache

services:
    - sqlite

before_script:
    - composer install
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    #- vendor/bin/phpunit
