language: php

sudo: true

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

cache:
    directories:
        - $HOME/.composer/cache

services:
    - sqlite

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

script:
    - vendor/sgsoft-studio/base/src
