language: php

sudo: true

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

cache:
    directories:
        - $HOME/.composer/cache

services:
    - mysql

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

    # copy .env
    - php -r "file_exists('.env') || copy('.env.example', '.env');"

    # dump autload
    - composer dump-autoload

    # prevent MySQL went away error
    - mysql -u root -e 'SET @@GLOBAL.wait_timeout=28800;'

    # Create a new database
    - mysql -u root -e "create database IF NOT EXISTS test;"
script:
    #
